name: vite build demo

# on:
#   release:
#     types: [created]

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm build
